ALTER TABLE `services` ADD `isVisible` int NOT NULL DEFAULT 1;
ALTER TABLE `services` ADD `isFeatured` int NOT NULL DEFAULT 0;
ALTER TABLE `tokenTransactions` ADD `balanceBefore` int NOT NULL DEFAULT 0;
CREATE INDEX `users_account_status_idx` ON `users` (`accountStatus`);
CREATE INDEX `token_transactions_user_created_idx` ON `tokenTransactions` (`userId`,`createdAt`);
CREATE INDEX `service_usage_user_created_idx` ON `serviceUsage` (`userId`,`createdAt`);
-- Seed defaults; INSERT IGNORE keeps existing administrator changes intact.

-- Seed defaults; INSERT IGNORE keeps existing administrator changes intact.
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('cheti-tin','CHETI CHA TIN','Pata cheti cha TIN kwa hatua rahisi.','file-badge',2,0,0,'Huduma kuu',0,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('thibitisha-tin','THIBITISHA TIN','Thibitisha taarifa za TIN yako.','badge-check',2,0,0,'Huduma kuu',1,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('nakala-nida','NAKALA LAINI YA NIDA','Omba nakala laini ya kitambulisho cha NIDA.','contact',2,0,0,'Huduma kuu',2,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('stika-lipa','STIKA ZA LIPA','Pata stika za LIPA kwa matumizi yako.','qr-code',2,0,0,'Huduma kuu',3,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('mpiga-kura','MPIGA KURA','Huduma na taarifa za mpiga kura.','vote',2,0,0,'Huduma kuu',4,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('leseni-biashara','LESENI YA BIASHARA','Anza mchakato wa leseni ya biashara.','store',2,0,0,'Huduma kuu',5,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('stika-mawakala','STIKA ZA MAWAKALA','Pata stika za mawakala.','ticket',2,0,0,'Huduma kuu',6,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('nakala-nida-2','NAKALA LAINI YA NIDA 2','Nakala nyingine ya taarifa za NIDA.','copy',2,0,0,'Huduma kuu',7,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('leseni-udereva','LESENI YA UDEREVA','Msaada wa huduma za leseni ya udereva.','car-front',2,0,0,'Huduma kuu',8,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('utafutaji-nida','UTAFUTA WA NIDA','Tafuta taarifa za NIDA bila tokeni.','search',0,1,0,'Huduma za bure',9,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('qr-mitandao','MSIMBO WA QR MITANDAO YOTE','Tengeneza msimbo wa QR wa mitandao yako.','qr-code',0,1,0,'Huduma za bure',10,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('brela','BRELA','Msaada wa huduma za BRELA.','landmark',2,0,0,'Huduma kuu',11,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('cheti-kuzaliwa','CHETI CHA KUZALIWA','Huduma hii inasubiri kufunguliwa.','baby',0,0,1,'Huduma zilizofungwa',12,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('visa-pasipoti','VISA / PASIPOTI','Huduma hii inasubiri kufunguliwa.','plane',0,0,1,'Huduma zilizofungwa',13,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('cheti-ndoa','CHETI CHA NDOA','Huduma hii inasubiri kufunguliwa.','heart-handshake',0,0,1,'Huduma zilizofungwa',14,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('ripoti-hasara','RIPOTI YA HASARA','Huduma hii inasubiri kufunguliwa.','file-warning',0,0,1,'Huduma zilizofungwa',15,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('tengeneza-muziki','TENGENEZA MUZIKI','Tengeneza wazo la muziki wa kipekee.','music-2',2,0,0,'Zana za ziada',16,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('tafuta-kvar-picha','TAFUTA KVAR PICHA','Tafuta picha kwa matumizi yako.','image-search',2,0,0,'Zana za ziada',17,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('simu-ya-tafuta','SIMU YA TAFTA','Pata msaada wa utafutaji wa simu.','smartphone',2,0,0,'Zana za ziada',18,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('usuli-wa-ondoa','USULI WA ONDOA','Ondoa usuli wa picha.','scan-face',2,0,0,'Zana za ziada',19,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('wasifu-chonga','WASIFU WA CHONGA','Tengeneza wasifu wa kuvutia.','user-round-pen',2,0,0,'Zana za ziada',20,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('nembo-chonga','NEMBO YA CHONGA','Tengeneza wazo la nembo.','palette',2,0,0,'Zana za ziada',21,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('radio-maria','RADIO MARIA','Fungua Radio Maria kwa urahisi.','radio',2,0,0,'Zana za ziada',22,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('simba-sc','SIMBA SC','Habari na huduma za Simba SC.','trophy',2,0,0,'Zana za ziada',23,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('yanga-africans','YANGA AFRICANS','Habari na huduma za Yanga Africans.','star',2,0,0,'Zana za ziada',24,1,0);
INSERT IGNORE INTO `services` (`slug`,`name`,`description`,`icon`,`tokenCost`,`isFree`,`isLocked`,`category`,`sortOrder`,`isVisible`,`isFeatured`) VALUES ('azam-tv','AZAM TV','Fungua huduma ya Azam TV.','tv',2,0,0,'Zana za ziada',25,1,0);
INSERT IGNORE INTO `roles` (`slug`,`name`,`description`) VALUES ('super_admin','Super Admin','Full system access'),('admin','Admin','Assigned administrative access'),('moderator','Moderator','Moderation access'),('support','Support','Support access'),('service_manager','Service Manager','Service catalog access'),('user','User','Standard user access');
INSERT IGNORE INTO `permissions` (`slug`,`name`) VALUES ('users.view','View users'),('users.manage','Manage users'),('users.roles','Manage roles'),('users.permissions','Manage permissions'),('tokens.manage','Manage tokens'),('services.manage','Manage services'),('settings.manage','Manage settings'),('analytics.view','View analytics'),('messages.manage','Manage messages'),('ads.manage','Manage advertisements');
